[package]
name = "entity_data"
version = "0.2.0"
authors = ["a7292969 <a7292969@gmail.com>"]
edition = "2018"
keywords = ["data", "interfaces", "dynamic-dispatch", "ecs"]
categories = ["data-structures", "rust-patterns"]
description = "A container for entity component data."
repository = "https://github.com/a7292969/entity_data"
readme = "README.md"
license-file = "LICENSE.md"

[dependencies]
ahash = "0.7.2"
bit-set = "0.5.2"
unchecked_unwrap = "3.0.0"

[dev-dependencies]
rand = "0.8.3"
